// client/src/components/AvatarPicker.tsx
const avatars = ['🐶','🐱','🦊','🐻','🐼','🐨','🐯','🦁','🐸','🐵'];

export default function AvatarPicker({ onSelect }: { onSelect: (a: string) => void }) {
  return (
    <div className="grid grid-cols-5 gap-4">
      {avatars.map(a => (
        <button key={a} onClick={() => onSelect(a)} className="text-5xl hover:scale-125 transition p-2 rounded-2xl active:bg-slate-100">{a}</button>
      ))}
    </div>
  );
}

// client-vue/components/AvatarPicker.vue
<script setup lang="ts">
const avatars = ['🐶', '🐱', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐸', '🐵']

defineProps<{
  modelValue: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const select = (avatar: string) => {
  emit('update:modelValue', avatar)
}
</script>

<template>
  <div class="grid grid-cols-5 gap-4">
    <button
      v-for="a in avatars"
      :key="a"
      type="button"
      class="text-5xl hover:scale-125 transition p-2 rounded-2xl active:bg-slate-100"
      @click="select(a)"
    >
      {{ a }}
    </button>
  </div>
</template>
